### ISSUE TITLE
Compatibility with HACS

### ISSUE THREAD

**Issue by lociii** [Sanderhuisman/home-assistant-custom-components#13]
Hey Sander,

thanks for the great work on these components.
Would you mind making them compatible with [HACS](https://hacs.netlify.com/) - the home assistant community store? So that HA users can easily install your component with just a few clicks.
If so, I would like to support as I already made some changes in my fork. However HACS supports one extension per repository so yours would have to be splitted.

Let me know if you're interested!

Best, Jens

**Comment by aptonline** [comment]
I too would be be interested in this , attempting to add manually via HACS fails due to the one extension per repository I think.

**Comment by ualex73** [comment]
The repo will/has moved to:
https://github.com/Sanderhuisman/docker_monitor

So that one should technically work with HACS ;-)

**Comment by lociii** [comment]
> The repo will/has moved to:
> https://github.com/Sanderhuisman/docker_monitor
> 
> So that one should technically work with HACS ;-)

Awesome. Thanks a lot!
I will close this issue now since I created it for the docker part of your components which is standalone now.
