### ISSUE TITLE
Docker Monitor: added HACS Support

### ISSUE THREAD

**Issue by brianhanifin** [Sanderhuisman/home-assistant-custom-components#18]
I split Docker Monitor [into a new repository](https://github.com/brianhanifin/docker-monitor).

Changes:
- Renamed repository: "home-assistant-custom-components" -> "docker-monitor"
- Removed: **/sensor/eetlijst.py** and **/sensor/luftdaten_cu.py**
- Moved folder: **/docker_monitor** to **/custom_components/docker_monitor**
- Updated: new urls in **/custom_updater.json**
- Added **info.md**: HACS short description display file
- Added **/hacs.json**
- Added **/custom_components/docker_monitor/manifest.json**
- README.md: HACS documentation added, references to other components removed
- Version bump: 0.0.3 -> 0.0.4
- Release: used [Github **Release** mechanism](https://github.com/brianhanifin/docker-monitor/releases) so HACS can see the current release version

**Comment by brianhanifin** [comment]
I am not submitting a pull request because I do not believe you would want to overwrite your original repository. It contains the complete commit history from your current repository.

The only code I touched in /custom_components/docker_monitor was the version number. I thought it made sense to increase the version number to make sure there aren't any problems with HACS users updating a manually installed version of your component.

Unfortunately, I am running hass.io, so it appears I cannot make use of this component after all. But you are welcome to fork [this repository](https://github.com/brianhanifin/docker-monitor) and make it your own.  If you have any questions, please let me know.

**Comment by Sanderhuisman** [comment]
Hi Brian,

I already made my own repository with the docker sensor only (and added support for HACS). You can find this repository in my repository list.

HASSIO is also using docker, however I have to find a way how to expose the docker socket (I already have a little script that can expose the docker socket over a TCP endpoint, but I don't know how it can be used on hassio)

**Comment by SAOPP** [comment]
Guys, it's very useful integration. could u please fix adding for latest version of HASC? At current the last version of HASC this is not possible because:

```
An error ocoured while processing
Exception: HacsException
Message: GitHub returned 404 for https://api.github.com/repos/Sanderhuisman/docker-monitor
Could not add this repository, make sure it is compliant with HACS.
```
