### ISSUE TITLE
Container uptime?

### ISSUE THREAD

**Issue by ualex73** [Sanderhuisman/home-assistant-custom-components#2]
I like the docker monitor, but i am only missing the uptime of each container. Is it possible to add this too?

**Comment by Sanderhuisman** [comment]
Hi Alexander,

I've been on a short holiday and haven't been behind my laptop for the last days;) I added an initial up time sensor which you can test with branch 'feature/2' (the ID of this feature). I will work on it further during the week.

**Comment by ualex73** [comment]
Hi Sander,

Np, holiday is always nice and best not to bring your laptop ;-)

Ok, i will test it tomorrow, but the "uptime" is similar to the "docker ps" output? Like the following example:
`$ docker ps -a`
`60440cfbd8f3        homeassistant/home-assistant:0.86.2       "python -m homeassis…"   24 hours ago        Up 11 hours hass`
`981139a2f69f        ualex73/devolo-avpromanager:1.0           "/init"                  5 weeks ago        Exited (0) 4 weeks ago avpro`

So the **Up 11 hours** and **Exited (0) 4 weeks ago**

Regards,
Alex

**Comment by Sanderhuisman** [comment]
I took the start time of the container for the up time sensor, so the value itself is the date the container started and HA shows that as uptime (as I marked that specific sensor value as timestamp device class).

I merged the branch with the master, but I will keep this issue open for feedback ;)
